AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless microservice using API Gateway, Lambda, and DynamoDB
Parameters:
  TableName:
    Type: String
Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: TableName
Metadata:
  AWS::ServerlessRepo::Application:
    Name: microservice
    Description: Serverless microservice using API Gateway, Lambda, and DynamoDB
    Author: Bernd Straehle
    SemanticVersion: 1.0.0
Resources:
  microservicehttpendpointpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Description: Serverless microservice using API Gateway, Lambda, and DynamoDB
      Timeout: 10
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: ANY
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName:
        Ref: TableName